name: AWS CDK Deploy
on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
permissions:
  id-token: write
  contents: read
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.AWS_DEPLOY_ROLE}}
          role-duration-seconds: 1200
          role-session-name: GithubActionsStockSwingTrader
      - name: CDK Diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: diff
          actions_comment: true
      - name: CDK Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: deploy
          cdk_stack: StockSwingTraderStack
          cdk_args: --require-approval never
          actions_comment: false